name: Build and Publish Docker Image

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build-and-publish:
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository
            - name: Checkout code
              uses: actions/checkout@v3

            # Log in to GitHub Container Registry
            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            # Build the Docker image
            - name: Build Docker Image
              run: |
                  docker build -f Dockerfile.prolog -t ghcr.io/${{ github.repository_owner }}/prolog-base-q:latest .

            # Push the Docker image to GitHub Container Registry
            - name: Push Docker Image
              run: |
                  docker push ghcr.io/${{ github.repository_owner }}/prolog-base-q:latest
