name: Build and Publish Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and Push Base Prolog Image
      - name: Build and Push Base Prolog Image
        run: |
          docker build -f Dockerfile.prolog -t dushess/prolog-queue-communication:base .
          docker push dushess/prolog-queue-communication:base

      # Build and Push dbus Image
      - name: Build and Push dbus Image
        run: |
          docker build -f dbus/Dockerfile.dbus -t dushess/prolog-queue-communication:dbus .
          docker push dushess/prolog-queue-communication:dbus

      # Build and Push mqtt Image
      - name: Build and Push mqtt Image
        run: |
          docker build -f mqtt/Dockerfile.mqtt -t dushess/prolog-queue-communication:mqtt .
          docker push dushess/prolog-queue-communication:mqtt

      # Build and Push rabbitmq Image
      - name: Build and Push rabbitmq Image
        run: |
          docker build -f rabbitmq/Dockerfile.rabbitmq -t dushess/prolog-queue-communication:rabbitmq .
          docker push dushess/prolog-queue-communication:rabbitmq

      # Build and Push stomp Image
      - name: Build and Push stomp Image
        run: |
          docker build -f stomp/Dockerfile.stomp -t dushess/prolog-queue-communication:stomp .
          docker push dushess/prolog-queue-communication:stomp
