name: Build and Publish Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the main repository
      - name: Checkout main repository
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and Push Base Prolog Image
      - name: Build and Push Base Prolog Image
        run: |
          docker build -f Dockerfile.prolog -t dushess/prolog-queue-communication:base .
          docker push dushess/prolog-queue-communication:base

      # Clone and Build dbus Repository
      - name: Clone and Build dbus Repository
        run: |
          git clone https://github.com/username/dbus-repo.git dbus
          cd dbus
          docker build -f Dockerfile.dbus -t dushess/prolog-queue-communication:dbus .
          docker push dushess/prolog-queue-communication:dbus

      # Clone and Build mqtt Repository
      - name: Clone and Build mqtt Repository
        run: |
          git clone https://github.com/username/mqtt-repo.git mqtt
          cd mqtt
          docker build -f Dockerfile.mqtt -t dushess/prolog-queue-communication:mqtt .
          docker push dushess/prolog-queue-communication:mqtt

      # Clone and Build rabbitmq Repository
      - name: Clone and Build rabbitmq Repository
        run: |
          git clone https://github.com/username/rabbitmq-repo.git rabbitmq
          cd rabbitmq
          docker build -f Dockerfile.rabbitmq -t dushess/prolog-queue-communication:rabbitmq .
          docker push dushess/prolog-queue-communication:rabbitmq
