name: Build and Publish Docker Image to Docker Hub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -f Dockerfile.prolog -t dushess/prolog-queue-communication:latest .

      # Push the Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push dushess/prolog-queue-communication:latest
